bin/iptables-flush: rewrite; and new symlink bin/ip6tables-flush pointing to the new iptables-flush

diff --git a/bin/iptables-flush b/bin/iptables-flush
--- a/bin/iptables-flush
+++ b/bin/iptables-flush
@@ -6,13 +6,33 @@ source "$LIB_PATH"/functions.bash || exit 1
 # Ensure /sbin and /usr/sbin are in PATH
 export PATH="/sbin:/usr/sbin:$PATH"
 
-iptables -P INPUT ACCEPT
-iptables -P FORWARD ACCEPT
-iptables -P OUTPUT ACCEPT
-iptables -t nat -F
-iptables -t mangle -F
-iptables -t raw -F
-iptables -F
-iptables -X
+case "$(basename "$0")" in
+  iptables-flush)  IPTABLES=iptables ;;
+  ip6tables-flush) IPTABLES=ip6tables ;;
+  *)               die "unable to determine needed iptables program based on script filename (\$0='$0')"
+esac
+
+for table in filter mangle nat raw
+do
+  #$IPTABLES -t $table -nL >/dev/null 2>&1 || continue
+
+  $IPTABLES -F
+  $IPTABLES -X
+  $IPTABLES -Z
+done
+
+for c in {PRE,POST}ROUTING
+do
+  $IPTABLES -t nat -F $c
+  $IPTABLES -t nat -Z $c
+done
+
+$IPTABLES -F
+$IPTABLES -X
+$IPTABLES -Z
+
+$IPTABLES -P INPUT ACCEPT
+$IPTABLES -P FORWARD ACCEPT
+$IPTABLES -P OUTPUT ACCEPT
 
 ## vim: ts=2 sw=2 et fdm=marker :
